using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MCCommandGenerator
{
    public static class Text
    {
        public static string[] Commands = {"advancement",
                                           "attribute",
                                           "ban",
                                           "ban-ip",
                                           "banlist",
                                           "bossbar",
                                           "clear",
                                           "clone",
                                           "data",
                                           "datapack",
                                           "debug",
                                           "defaultgamemode",
                                           "deop",
                                           "difficulty",
                                           "effect",
                                           "enchant",
                                           "execute",
                                           "experience",
                                           "fill",
                                           "forceload",
                                           "function",
                                           "gamemode",
                                           "gamerule",
                                           "give",
                                           "help",
                                           "kick",
                                           "kill",
                                           "list",
                                           "locate",
                                           "locatebiome",
                                           "loot",
                                           "me",
                                           "msg",
                                           "op",
                                           "pardon",
                                           "particle",
                                           "playsound",
                                           "publish",
                                           "recipe",
                                           "reload",
                                           "replaceitem",
                                           "save-all",
                                           "save-off",
                                           "save-on",
                                           "say",
                                           "schedule",
                                           "scoreboard",
                                           "seed",
                                           "setblock",
                                           "setidletimeout",
                                           "setworldspawn",
                                           "spawnpoint",
                                           "spectate",
                                           "spreadplayers",
                                           "stop",
                                           "stopsound",
                                           "summon",
                                           "tag",
                                           "team",
                                           "teammsg",
                                           "teleport",
                                           "tell",
                                           "tellraw",
                                           "time",
                                           "title",
                                           "tp",
                                           "trigger",
                                           "w",
                                           "weather",
                                           "whitelist",
                                           "worldboarder",
                                           "xp"
                                          };
        public static string[] Selectors = { "@a",
                                             "@e",
                                             "@p",
                                             "@r",
                                             "@s"
                                           };
        public static string[] Advancements = { "Adventure: Adventure Time",
                                                "Adventure: Arbalistic",
                                                "Adventure: Bullseye",
                                                "Adventure: Hero of the Village",
                                                "Adventure: Honey Block Slide",
                                                "Adventure: Kill a Mob",
                                                "Adventure: Kill all mobs",
                                                "Adventure: Ol' Betsy",
                                                "Adventure: Root",
                                                "Adventure: Shoot Arrow",
                                                "Adventure: Sleep in Bed",
                                                "Adventure: Sniper Duel",
                                                "Adventure: Summon Iron Golem",
                                                "Adventure: Throw Trident",
                                                "Adventure: Totem of Undying",
                                                "Adventure: Trade",
                                                "Adventure: Two Birds, One Arrow",
                                                "Adventure: Very Very Frightening",
                                                "Adventure: Volntary Exile",
                                                "Adventure: Who's the pillager now",
                                                "End: Dragon Breath",
                                                "End: Dragon Egg",
                                                "End: Elytra",
                                                "End: Enter End Getaway",
                                                "End: Find End City",
                                                "End: Kill Dragon",
                                                "End: Levitate",
                                                "End: Respawn Dragon",
                                                "End: Root",
                                                "Husbandry: Balanced Diet",
                                                "Husbandry: Bred All Animals",
                                                "Husbandry: Breed An Animal",
                                                "Husbandry: Complete Catalogue",
                                                "Husbandry: Fishy Business",
                                                "Husbandry: Obtain Netherite Hoe",
                                                "Husbandry: Plant Seed",
                                                "Husbandry: Root",
                                                "Husbandry: Safely Harvest Honey",
                                                "Husbandry: Silk Touch Nest",
                                                "Husbandry: Tactical Fishing",
                                                "Husbandry: Tame an Animal",
                                                "Nether: All Effects",
                                                "Nether: All Potions",
                                                "Nether: Brew Potion",
                                                "Nether: Charge Respawn Anchor",
                                                "Nether: Create Beacon",
                                                "Nether: Create Full Beacon",
                                                "Nether: Distract Piglin",
                                                "Nether: Explore Nether",
                                                "Nether: Fast Travel",
                                                "Nether: Find Bastion",
                                                "Nether: Find Fortress",
                                                "Nether: Get Wither Skull",
                                                "Nether: Loot Bastion",
                                                "Nether: Netherite Armor",
                                                "Nether: Obtain Ancient Debris",
                                                "Nether: Obtain Blaze Rod",
                                                "Nether: Obtain Crying Obsidian",
                                                "Nether: Return to Sender",
                                                "Nether: Ride Strider",
                                                "Nether: Root",
                                                "Nether: Summon Wither",
                                                "Nether: Uneasy Alliance",
                                                "Nether: Use Lodestone",
                                                "Story: Cure Zombie Villager",
                                                "Story: Deflect Arrow",
                                                "Story: Enchant Item",
                                                "Story: Enter the End",
                                                "Story: Enter the Nether",
                                                "Story: Follow Ender Eye",
                                                "Story: Form Obsidian",
                                                "Story: Iron Tools",
                                                "Story: Lava Bucket",
                                                "Story: Mine Diamond",
                                                "Story: Mine Stone",
                                                "Story: Obtain Armor",
                                                "Story: Root",
                                                "Story: Shiny Gear",
                                                "Story: Smelt Iron",
                                                "Story: Upgrade Tools"
                                              };
        public static string[] Gamemodes = { "Survival",
                                             "Creative",
                                             "Adventure",
                                             "Spectator"                                                  
                                           };
        public static string[] Sorts = {"nearest",
                                        "furthest",
                                        "random",
                                        "arbitrary"
                                       };
        public static string[] Types = { "#Arrows",
                                         "#Beehive Inhabitors",
                                         "#Impact Projectiles",
                                         "#Raiders",
                                         "#Skeletons",
                                         "Area Effect Cloud",
                                         "Armor Stand",
                                         "Arrow",
                                         "Bat",
                                         "Bee",
                                         "Blaze",
                                         "Boat",
                                         "Cat",
                                         "Cave Spider",
                                         "Chest Minecart",
                                         "Chicken",
                                         "Cod",
                                         "Command Block Minecart",
                                         "Cow",
                                         "Creeper",
                                         "Dolphin",
                                         "Donkey",
                                         "Dragon Fireball",
                                         "Drowned",
                                         "Egg",
                                         "Elder Guardian",
                                         "End Crystal",
                                         "Ender Dragon",
                                         "Ender Pearl",
                                         "Enderman",
                                         "Endermite",
                                         "Evoker",
                                         "Evoker Fangs",
                                         "Experience Bottle",
                                         "Experience Orb",
                                         "Eye of Ender",
                                         "Falling Block",
                                         "Fireball",
                                         "Firework Rocket",
                                         "Fishing Bobber",
                                         "Fox",
                                         "Furnace Minecart",
                                         "Ghast",
                                         "Giant",
                                         "Guardian",
                                         "Hoglin",
                                         "Hopper Minecart",
                                         "Horse",
                                         "Husk",
                                         "Illusioner",
                                         "Iron Golem",
                                         "Item",
                                         "Item Frame",
                                         "Leash Knot",
                                         "Lightning Bolt",
                                         "Llama",
                                         "Llama Spit",
                                         "Magma Cube",
                                         "Minecart",
                                         "Mooshroom",
                                         "Mule",
                                         "Ocelot",
                                         "Painting",
                                         "Panda",
                                         "Parrot",
                                         "Phantom",
                                         "Pig",
                                         "Piglin",
                                         "Piglin Brute",
                                         "Pillager",
                                         "Player",
                                         "Polar Bear",
                                         "Potion",
                                         "Pufferfish",
                                         "Rabbit",
                                         "Ravager",
                                         "Salmon",
                                         "Sheep",
                                         "Shulker",
                                         "Shulker Bullet",
                                         "Silverfish",
                                         "Skeleton",
                                         "Skeleton Horse",
                                         "Slime",
                                         "Small Fireball",
                                         "Snow Golem",
                                         "Snowball",
                                         "Spawner Minecart",
                                         "Spectral Arrow",
                                         "Spider",
                                         "Squid",
                                         "Stray",
                                         "Strider",
                                         "TNT",
                                         "TNT Minecart",
                                         "Trader Llama",
                                         "Trident",
                                         "Tropical Fish",
                                         "Turtle",
                                         "Vex",
                                         "Villager",
                                         "Vindicator",
                                         "Wandering Trader",
                                         "Witch",
                                         "Wither",
                                         "Wither Skeleton",
                                         "Wither Skull",
                                         "Wolf",
                                         "Zoglin",
                                         "Zombie",
                                         "Zombie Horse",
                                         "Zombie Villager",
                                         "Zombified Piglin"
                                        };
        public static string[] RecipesBuilding = { "Acacia Planks",
                                                   "Acacia Slab",
                                                   "Acacia Stairs",
                                                   "Acacia Wood",
                                                   "Andesite",
                                                   "Andesite Slab",
                                                   "Andesite Slab (Stonecutter)",
                                                   "Andesite Stairs",
                                                   "Andesite Stairs (Stonecutter)",
                                                   "Birch Planks",
                                                   "Birch Slab",
                                                   "Birch Stairs",
                                                   "Birch Wood",
                                                   "Black Concrete Powder",
                                                   "Black Stained Glass",
                                                   "Black Terracotta",
                                                   "Black Wool",
                                                   "Blackstone Slab",
                                                   "Blackstone Slab (Stonecutter)",
                                                   "Blackstone Stairs",
                                                   "Blackstone Stairs (Stonecutter)",
                                                   "Blue Concrete Powder",
                                                   "Blue Ice",
                                                   "Blue Stained Glass",
                                                   "Blue Terracotta",
                                                   "Blue Wool",
                                                   "Bone Block",
                                                   "Bookshelf",
                                                   "Brick Slab",
                                                   "Brick Slab (Stonecutter)",
                                                   "Brick Stairs",
                                                   "Brick Stairs (Stonecutter)",
                                                   "Bricks",
                                                   "Brown Concrete Powder",
                                                   "Brown Stained Glass",
                                                   "Brown Terracotta",
                                                   "Brown Wool",
                                                   "Chiseled Nether Bricks",
                                                   "Chiseled Nether Bricks (Stonecutter)",
                                                   "Chiseled Polished Blackstone",
                                                   "Chiseled Polished Blackstone (Stonecutter (from Blackstone))",
                                                   "Chiseled Polished Blackstone (Stonecutter (from Polished Blackstone))",
                                                   "Chiseled Quartz Block",
                                                   "Chiseled Quartz Block (Stonecutter)",
                                                   "Chiseled Red Sandstone",
                                                   "Chiseled Red Sandstone (Stonecutter)",
                                                   "Chiseled Sandstone",
                                                   "Chiseled Sandstone (Stonecutter)",
                                                   "Chiseled Stone Bricks",
                                                   "Chiseled Stone Bricks (Stonecutter (from Stone Bricks))",
                                                   "Chiseled Stone Bricks (Stonecutter (from Stone))",
                                                   "Clay",
                                                   "Coal Block",
                                                   "Coarse Dirt",
                                                   "Cobblestone Slab",
                                                   "Cobblestone Slab (Stonecutter)",
                                                   "Cobblestone Stairs",
                                                   "Cobblestone Stairs (Stonecutter)",
                                                   "Cracked Nether Bricks",
                                                   "Cracked Polished Blackstone Bricks",
                                                   "Cracked Stone Bricks",
                                                   "Crimson Hyphae",
                                                   "Crimson Planks",
                                                   "Crimson Slab",
                                                   "Crimson Stairs",
                                                   "Cut Red Sandstone",
                                                   "Cut Red Sandstone (Stonecutter)",
                                                   "Cut Red Sandstone Slab",
                                                   "Cut Red Sandstone Slab (Stonecutter (from Cut Red Sandstone))",
                                                   "Cut Red Sandstone Slab (Stonecutter (from Red Sandstone))",
                                                   "Cut Sandstone",
                                                   "Cut Sandstone (Stonecutter)",
                                                   "Cut Sandstone Slab",
                                                   "Cut Sandstone Slab (Stonecutter (from Cut Sandstone))",
                                                   "Cut Sandstone Slab (Stonecutter (from Sandstone))",
                                                   "Cyan Concrete Powder",
                                                   "Cyan Stained Glass",
                                                   "Cyan Terracotta",
                                                   "Cyan Wool",
                                                   "Dark Oak Planks",
                                                   "Dark Oak Slab",
                                                   "Dark Oak Stairs",
                                                   "Dark Oak Wood",
                                                   "Dark Prismarine",
                                                   "Dark Prismarine Slab",
                                                   "Dark Prismarine Slab (Stonecutter)",
                                                   "Dark Prismarine Stairs",
                                                   "Dark Prismarine Stairs (Stonecutter)",
                                                   "Diamond Block",
                                                   "Diorite",
                                                   "Diorite Slab",
                                                   "Diorite Slab (Stonecutter)",
                                                   "Diorite Stairs",
                                                   "Diorite Stairs (Stonecutter)",
                                                   "Dried Kelp Block",
                                                   "Emerald Block",
                                                   "End Stone Brick Slab",
                                                   "End Stone Brick Slab (Stonecutter (from End Stone Bricks))",
                                                   "End Stone Brick Slab (Stonecutter (from End Stone))",
                                                   "End Stone Brick Stairs",
                                                   "End Stone Brick Stairs (Stonecutter (from End Stone Bricks))",
                                                   "End Stone Brick Stairs (Stonecutter (from End Stone))",
                                                   "End Stone Bricks",
                                                   "End Stone Bricks (Stonecutter)",
                                                   "Glass",
                                                   "Glowstone",
                                                   "Gold Block",
                                                   "Granite",
                                                   "Granite Slab",
                                                   "Granite Slab (Stonecutter)",
                                                   "Granite Stairs",
                                                   "Granite Stairs (Stonecutter)",
                                                   "Gray Concrete Powder",
                                                   "Gray Stained Glass",
                                                   "Gray Terracotta",
                                                   "Gray Wool",
                                                   "Green Concrete Powder",
                                                   "Green Stained Glass",
                                                   "Green Terracotta",
                                                   "Green Wool",
                                                   "Hay Block",
                                                   "Iron Block",
                                                   "Jack o' Lantern",
                                                   "Jungle Planks",
                                                   "Jungle Slab",
                                                   "Jungle Stairs",
                                                   "Jungle Wood",
                                                   "Lapis Block",
                                                   "Light Blue Concrete Powder",
                                                   "Light Blue Stained Glass",
                                                   "Light Blue Terracotta",
                                                   "Light Blue Wool",
                                                   "Light Gray Concrete Powder",
                                                   "Light Gray Stained Glass",
                                                   "Light Gray Terracotta",
                                                   "Light Gray Wool",
                                                   "Lime Concrete Powder",
                                                   "Lime Stained Glass",
                                                   "Lime Terracotta",
                                                   "Lime Wool",
                                                   "Magenta Concrete Powder",
                                                   "Magenta Stained Glass",
                                                   "Magenta Terracotta",
                                                   "Magenta Wool",
                                                   "Magma Block",
                                                   "Melon",
                                                   "Mossy Cobblestone",
                                                   "Mossy Cobblestone Slab",
                                                   "Mossy Cobblestone Slab (Stonecutter)",
                                                   "Mossy Cobblestone Stairs",
                                                   "Mossy Cobblestone Stairs (Stonecutter)",
                                                   "Mossy Stone Brick Slab",
                                                   "Mossy Stone Brick Slab (Stonecutter)",
                                                   "Mossy Stone Brick Stairs",
                                                   "Mossy Stone Brick Stairs (Stonecutter)",
                                                   "Mossy Stone Bricks",
                                                   "Nether Brick Slab",
                                                   "Nether Brick Slab (Stonecutter)",
                                                   "Nether Brick Stairs",
                                                   "Nether Brick Stairs (Stonecutter)",
                                                   "Nether Bricks",
                                                   "Nether Wart Block",
                                                   "Netherite Block",
                                                   "Oak Planks",
                                                   "Oak Slab",
                                                   "Oak Stairs",
                                                   "Oak Wood",
                                                   "Orange Concrete Powder",
                                                   "Orange Stained Glass",
                                                   "Orange Terracotta",
                                                   "Orange Wool",
                                                   "Packed Ice",
                                                   "Pink Concrete Powder",
                                                   "Pink Stained Glass",
                                                   "Pink Terracotta",
                                                   "Pink Wool",
                                                   "Polished Andesite",
                                                   "Polished Andesite (Stonecutter)",
                                                   "Polished Andesite Slab",
                                                   "Polished Andesite Slab (Stonecutter (from Andesite))",
                                                   "Polished Andesite Slab (Stonecutter (from Polished Andesite))",
                                                   "Polished Andesite Stairs",
                                                   "Polished Andesite Stairs (Stonecutter (from Andesite))",
                                                   "Polished Andesite Stairs (Stonecutter (from Polished Andesite))",
                                                   "Polished Basalt",
                                                   "Polished Basalt (Stonecutter)",
                                                   "Polished Blackstone",
                                                   "Polished Blackstone (Stonecutter)",
                                                   "Polished Blackstone Brick Slab",
                                                   "Polished Blackstone Brick Slab (Stonecutter (from Blackstone))",
                                                   "Polished Blackstone Brick Slab (Stonecutter (from Polished Blackstone Bricks))",
                                                   "Polished Blackstone Brick Slab (Stonecutter (from Polished Blackstone))",
                                                   "Polished Blackstone Brick Stairs",
                                                   "Polished Blackstone Brick Stairs (Stonecutter (from Blackstone))",
                                                   "Polished Blackstone Brick Stairs (Stonecutter (from Polished Blackstone Bricks))",
                                                   "Polished Blackstone Brick Stairs (Stonecutter (from Polished Blackstone))",
                                                   "Polished Blackstone Bricks",
                                                   "Polished Blackstone Bricks (Stonecutter (from Blackstone))",
                                                   "Polished Blackstone Bricks (Stonecutter (from Polished Blackstone))",
                                                   "Polished Blackstone Slab",
                                                   "Polished Blackstone Slab (Stonecutter (from Blackstone))",
                                                   "Polished Blackstone Slab (Stonecutter (from Polished Blackstone))",
                                                   "Polished Blackstone Stairs",
                                                   "Polished Blackstone Stairs (Stonecutter (from Blackstone))",
                                                   "Polished Blackstone Stairs (Stonecutter (from Polished Blackstone))",
                                                   "Polished Diorite",
                                                   "Polished Diorite (Stonecutter)",
                                                   "Polished Diorite Slab (Stonecutter (from Diorite))",
                                                   "Polished Diorite Slab (Stonecutter (from Polished Diorite))",
                                                   "Polished Diorite Stairs",
                                                   "Polished Diorite Stairs (Stonecutter (from Diorite))",
                                                   "Polished Diorite Stairs (Stonecutter (from Polished Diorite))",
                                                   "Polished Granite",
                                                   "Polished Granite (Stonecutter)",
                                                   "Polished Granite Slab",
                                                   "Polished Granite Slab (Stonecutter (from Granite))",
                                                   "Polished Granite Slab (Stonecutter (from Polished Granite))",
                                                   "Polished Granite Stairs",
                                                   "Polished Granite Stairs (Stonecutter (from Granite))",
                                                   "Polished Granite Stairs (Stonecutter (from Polished Granite))",
                                                   "Prismarine",
                                                   "Prismarine Brick Slab",
                                                   "Prismarine Brick Slab (Stonecutter)",
                                                   "Prismarine Brick Stairs",
                                                   "Prismarine Brick Stairs (Stonecutter)",
                                                   "Prismarine Bricks",
                                                   "Prismarine Slab",
                                                   "Prismarine Slab (Stonecutter)",
                                                   "Prismarine Stairs",
                                                   "Prismarine Stairs (Stonecutter)",
                                                   "Purple Concrete Powder",
                                                   "Purple Stained Glass",
                                                   "Purple Terracotta",
                                                   "Purple Wool",
                                                   "Purpur Block",
                                                   "Purpur Pillar",
                                                   "Purpur Pillar (Stonecutter)",
                                                   "Purpur Slab",
                                                   "Purpur Slab (Stonecutter)",
                                                   "Purpur Stairs",
                                                   "Purpur Stairs (Stonecutter)",
                                                   "Quartz Block",
                                                   "Quartz Bricks",
                                                   "Quartz Bricks (Stonecutter)",
                                                   "Quartz Pillar",
                                                   "Quartz Pillar (Stonecutter)",
                                                   "Quartz Slab",
                                                   "Quartz Slab (Stonecutter)",
                                                   "Quartz Stairs",
                                                   "Quartz Stairs (Stonecutter)",
                                                   "Red Concrete Powder",
                                                   "Red Nether Brick Slab",
                                                   "Red Nether Brick Slab (Stonecutter)",
                                                   "Red Nether Brick Stairs",
                                                   "Red Nether Brick Stairs (Stonecutter)",
                                                   "Red Nether Bricks",
                                                   "Red Sandstone",
                                                   "Red Sandstone Slab",
                                                   "Red Sandstone Slab (Stonecutter)",
                                                   "Red Sandstone Stairs",
                                                   "Red Sandstone Stairs (Stonecutter)",
                                                   "Red Stained Glass",
                                                   "Red Terracotta",
                                                   "Red Wool"
                                                 };
        public static string[] RecipesDecoration = { "",
                                                     "",
                                                     ""
                                                   };
        public static string[] RecipesRedstone = { "",
                                                   "",
                                                   ""
                                                 };
        public static string[] RecipesTransportation = { "",
                                                         "",
                                                         ""
                                                       };
        public static string[] RecipesMisc = { "",
                                               "",
                                               ""
                                             };
        public static string[] RecipesFood = { "",
                                               "",
                                               ""
                                             };
        public static string[] RecipesTools = { "",
                                                "",
                                                ""
                                              };
        public static string[] RecipesCombat = { "",
                                                 "",
                                                 ""
                                               };
        public static string[] RecipesBrewing = { "",
                                                  "",
                                                  ""
                                                };
    }
}
