using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MCCommandGenerator
{
    public static class Text
    {
        public static string[] Commands = {"advancement",
                                           "attribute",
                                           "ban",
                                           "ban-ip",
                                           "banlist",
                                           "bossbar",
                                           "clear",
                                           "clone",
                                           "data",
                                           "datapack",
                                           "debug",
                                           "defaultgamemode",
                                           "deop",
                                           "difficulty",
                                           "effect",
                                           "enchant",
                                           "execute",
                                           "experience",
                                           "fill",
                                           "forceload",
                                           "function",
                                           "gamemode",
                                           "gamerule",
                                           "give",
                                           "help",
                                           "kick",
                                           "kill",
                                           "list",
                                           "locate",
                                           "locatebiome",
                                           "loot",
                                           "me",
                                           "msg",
                                           "op",
                                           "pardon",
                                           "particle",
                                           "playsound",
                                           "publish",
                                           "recipe",
                                           "reload",
                                           "replaceitem",
                                           "save-all",
                                           "save-off",
                                           "save-on",
                                           "say",
                                           "schedule",
                                           "scoreboard",
                                           "seed",
                                           "setblock",
                                           "setidletimeout",
                                           "setworldspawn",
                                           "spawnpoint",
                                           "spectate",
                                           "spreadplayers",
                                           "stop",
                                           "stopsound",
                                           "summon",
                                           "tag",
                                           "team",
                                           "teammsg",
                                           "teleport",
                                           "tell",
                                           "tellraw",
                                           "time",
                                           "title",
                                           "tp",
                                           "trigger",
                                           "w",
                                           "weather",
                                           "whitelist",
                                           "worldboarder",
                                           "xp"
                                          };
        public static string[] Selectors = { "@a",
                                             "@e",
                                             "@p",
                                             "@r",
                                             "@s"
                                           };
        public static string[] Advancements = { "Adventure: Adventure Time",
                                                "Adventure: Arbalistic",
                                                "Adventure: Bullseye",
                                                "Adventure: Hero of the Village",
                                                "Adventure: Honey Block Slide",
                                                "Adventure: Kill a Mob",
                                                "Adventure: Kill all mobs",
                                                "Adventure: Ol' Betsy",
                                                "Adventure: Root",
                                                "Adventure: Shoot Arrow",
                                                "Adventure: Sleep in Bed",
                                                "Adventure: Sniper Duel",
                                                "Adventure: Summon Iron Golem",
                                                "Adventure: Throw Trident",
                                                "Adventure: Totem of Undying",
                                                "Adventure: Trade",
                                                "Adventure: Two Birds, One Arrow",
                                                "Adventure: Very Very Frightening",
                                                "Adventure: Volntary Exile",
                                                "Adventure: Who's the pillager now",
                                                "End: Dragon Breath",
                                                "End: Dragon Egg",
                                                "End: Elytra",
                                                "End: Enter End Getaway",
                                                "End: Find End City",
                                                "End: Kill Dragon",
                                                "End: Levitate",
                                                "End: Respawn Dragon",
                                                "End: Root",
                                                "Husbandry: Balanced Diet",
                                                "Husbandry: Bred All Animals",
                                                "Husbandry: Breed An Animal",
                                                "Husbandry: Complete Catalogue",
                                                "Husbandry: Fishy Business",
                                                "Husbandry: Obtain Netherite Hoe",
                                                "Husbandry: Plant Seed",
                                                "Husbandry: Root",
                                                "Husbandry: Safely Harvest Honey",
                                                "Husbandry: Silk Touch Nest",
                                                "Husbandry: Tactical Fishing",
                                                "Husbandry: Tame an Animal",
                                                "Nether: All Effects",
                                                "Nether: All Potions",
                                                "Nether: Brew Potion",
                                                "Nether: Charge Respawn Anchor",
                                                "Nether: Create Beacon",
                                                "Nether: Create Full Beacon",
                                                "Nether: Distract Piglin",
                                                "Nether: Explore Nether",
                                                "Nether: Fast Travel",
                                                "Nether: Find Bastion",
                                                "Nether: Find Fortress",
                                                "Nether: Get Wither Skull",
                                                "Nether: Loot Bastion",
                                                "Nether: Netherite Armor",
                                                "Nether: Obtain Ancient Debris",
                                                "Nether: Obtain Blaze Rod",
                                                "Nether: Obtain Crying Obsidian",
                                                "Nether: Return to Sender",
                                                "Nether: Ride Strider",
                                                "Nether: Root",
                                                "Nether: Summon Wither",
                                                "Nether: Uneasy Alliance",
                                                "Nether: Use Lodestone",
                                                "Story: Cure Zombie Villager",
                                                "Story: Deflect Arrow",
                                                "Story: Enchant Item",
                                                "Story: Enter the End",
                                                "Story: Enter the Nether",
                                                "Story: Follow Ender Eye",
                                                "Story: Form Obsidian",
                                                "Story: Iron Tools",
                                                "Story: Lava Bucket",
                                                "Story: Mine Diamond",
                                                "Story: Mine Stone",
                                                "Story: Obtain Armor",
                                                "Story: Root",
                                                "Story: Shiny Gear",
                                                "Story: Smelt Iron",
                                                "Story: Upgrade Tools"
                                              };
        public static string[] Gamemodes = { "Survival",
                                             "Creative",
                                             "Adventure",
                                             "Spectator"                                                  
                                           };
        public static string[] Sorts = {"nearest",
                                        "furthest",
                                        "random",
                                        "arbitrary"
                                       };
        public static string[] Types = { "#Arrows",
                                         "#Beehive Inhabitors",
                                         "#Impact Projectiles",
                                         "#Raiders",
                                         "#Skeletons",
                                         "Area Effect Cloud",
                                         "Armor Stand",
                                         "Arrow",
                                         "Bat",
                                         "Bee",
                                         "Blaze",
                                         "Boat",
                                         "Cat",
                                         "Cave Spider",
                                         "Chest Minecart",
                                         "Chicken",
                                         "Cod",
                                         "Command Block Minecart",
                                         "Cow",
                                         "Creeper",
                                         "Dolphin",
                                         "Donkey",
                                         "Dragon Fireball",
                                         "Drowned",
                                         "Egg",
                                         "Elder Guardian",
                                         "End Crystal",
                                         "Ender Dragon",
                                         "Ender Pearl",
                                         "Enderman",
                                         "Endermite",
                                         "Evoker",
                                         "Evoker Fangs",
                                         "Experience Bottle",
                                         "Experience Orb",
                                         "Eye of Ender",
                                         "Falling Block",
                                         "Fireball",
                                         "Firework Rocket",
                                         "Fishing Bobber",
                                         "Fox",
                                         "Furnace Minecart",
                                         "Ghast",
                                         "Giant",
                                         "Guardian",
                                         "Hoglin",
                                         "Hopper Minecart",
                                         "Horse",
                                         "Husk",
                                         "Illusioner",
                                         "Iron Golem",
                                         "Item",
                                         "Item Frame",
                                         "Leash Knot",
                                         "Lightning Bolt",
                                         "Llama",
                                         "Llama Spit",
                                         "Magma Cube",
                                         "Minecart",
                                         "Mooshroom",
                                         "Mule",
                                         "Ocelot",
                                         "Painting",
                                         "Panda",
                                         "Parrot",
                                         "Phantom",
                                         "Pig",
                                         "Piglin",
                                         "Piglin Brute",
                                         "Pillager",
                                         "Player",
                                         "Polar Bear",
                                         "Potion",
                                         "Pufferfish",
                                         "Rabbit",
                                         "Ravager",
                                         "Salmon",
                                         "Sheep",
                                         "Shulker",
                                         "Shulker Bullet",
                                         "Silverfish",
                                         "Skeleton",
                                         "Skeleton Horse",
                                         "Slime",
                                         "Small Fireball",
                                         "Snow Golem",
                                         "Snowball",
                                         "Spawner Minecart",
                                         "Spectral Arrow",
                                         "Spider",
                                         "Squid",
                                         "Stray",
                                         "Strider",
                                         "TNT",
                                         "TNT Minecart",
                                         "Trader Llama",
                                         "Trident",
                                         "Tropical Fish",
                                         "Turtle",
                                         "Vex",
                                         "Villager",
                                         "Vindicator",
                                         "Wandering Trader",
                                         "Witch",
                                         "Wither",
                                         "Wither Skeleton",
                                         "Wither Skull",
                                         "Wolf",
                                         "Zoglin",
                                         "Zombie",
                                         "Zombie Horse",
                                         "Zombie Villager",
                                         "Zombified Piglin"
                                        };
        public static string[] RecipesBuilding = { "Acacia Planks",
                                                   "Acacia Slab",
                                                   "Acacia Stairs",
                                                   "Acacia Wood",
                                                   "Andesite",
                                                   "Andesite Slab",
                                                   "Andesite Slab (Stonecutter)",
                                                   "Andesite Stairs",
                                                   "Andesite Stairs (Stonecutter)",
                                                   "Birch Planks",
                                                   "Birch Slab",
                                                   "Birch Stairs",
                                                   "Birch Wood",
                                                   "Black Concrete Powder",
                                                   "Black Stained Glass",
                                                   "Black Terracotta",
                                                   "Black Wool",
                                                   "Blackstone Slab",
                                                   "Blackstone Slab (Stonecutter)",
                                                   "Blackstone Stairs",
                                                   "Blackstone Stairs (Stonecutter)",
                                                   "Blue Concrete Powder",
                                                   "Blue Ice",
                                                   "Blue Stained Glass",
                                                   "Blue Terracotta",
                                                   "Blue Wool",
                                                   "Bone Block",
                                                   "Bookshelf",
                                                   "Brick Slab",
                                                   "Brick Slab (Stonecutter)",
                                                   "Brick Stairs",
                                                   "Brick Stairs (Stonecutter)",
                                                   "Bricks",
                                                   "Brown Concrete Powder",
                                                   "Brown Stained Glass",
                                                   "Brown Terracotta",
                                                   "Brown Wool",
                                                   "Chiseled Nether Bricks",
                                                   "Chiseled Nether Bricks (Stonecutter)",
                                                   "Chiseled Polished Blackstone",
                                                   "Chiseled Polished Blackstone (Stonecutter (from Blackstone))",
                                                   "Chiseled Polished Blackstone (Stonecutter (from Polished Blackstone))",
                                                   "Chiseled Quartz Block",
                                                   "Chiseled Quartz Block (Stonecutter)",
                                                   "Chiseled Red Sandstone",
                                                   "Chiseled Red Sandstone (Stonecutter)",
                                                   "Chiseled Sandstone",
                                                   "Chiseled Sandstone (Stonecutter)",
                                                   "Chiseled Stone Bricks",
                                                   "Chiseled Stone Bricks (Stonecutter (from Stone Bricks))",
                                                   "Chiseled Stone Bricks (Stonecutter (from Stone))",
                                                   "Clay",
                                                   "Coal Block",
                                                   "Coarse Dirt",
                                                   "Cobblestone Slab",
                                                   "Cobblestone Slab (Stonecutter)",
                                                   "Cobblestone Stairs",
                                                   "Cobblestone Stairs (Stonecutter)",
                                                   "Cracked Nether Bricks",
                                                   "Cracked Polished Blackstone Bricks",
                                                   "Cracked Stone Bricks",
                                                   "Crimson Hyphae",
                                                   "Crimson Planks",
                                                   "Crimson Slab",
                                                   "Crimson Stairs",
                                                   "Cut Red Sandstone",
                                                   "Cut Red Sandstone (Stonecutter)",
                                                   "Cut Red Sandstone Slab",
                                                   "Cut Red Sandstone Slab (Stonecutter (from Cut Red Sandstone))",
                                                   "Cut Red Sandstone Slab (Stonecutter (from Red Sandstone))",
                                                   "Cut Sandstone",
                                                   "Cut Sandstone (Stonecutter)",
                                                   "Cut Sandstone Slab",
                                                   "Cut Sandstone Slab (Stonecutter (from Cut Sandstone))",
                                                   "Cut Sandstone Slab (Stonecutter (from Sandstone))",
                                                   "Cyan Concrete Powder",
                                                   "Cyan Stained Glass",
                                                   "Cyan Terracotta",
                                                   "Cyan Wool",
                                                   "Dark Oak Planks",
                                                   "Dark Oak Slab",
                                                   "Dark Oak Stairs",
                                                   "Dark Oak Wood",
                                                   "Dark Prismarine",
                                                   "Dark Prismarine Slab",
                                                   "Dark Prismarine Slab (Stonecutter)",
                                                   "Dark Prismarine Stairs",
                                                   "Dark Prismarine Stairs (Stonecutter)",
                                                   "Diamond Block",
                                                   "Diorite",
                                                   "Diorite Slab",
                                                   "Diorite Slab (Stonecutter)",
                                                   "Diorite Stairs",
                                                   "Diorite Stairs (Stonecutter)",
                                                   "Dried Kelp Block",
                                                   "Emerald Block",
                                                   "End Stone Brick Slab",
                                                   "End Stone Brick Slab (Stonecutter (from End Stone Bricks))",
                                                   "End Stone Brick Slab (Stonecutter (from End Stone))",
                                                   "End Stone Brick Stairs",
                                                   "End Stone Brick Stairs (Stonecutter (from End Stone Bricks))",
                                                   "End Stone Brick Stairs (Stonecutter (from End Stone))",
                                                   "End Stone Bricks",
                                                   "End Stone Bricks (Stonecutter)",
                                                   "Glass",
                                                   "Glowstone",
                                                   "Gold Block",
                                                   "Granite",
                                                   "Granite Slab",
                                                   "Granite Slab (Stonecutter)",
                                                   "Granite Stairs",
                                                   "Granite Stairs (Stonecutter)",
                                                   "Gray Concrete Powder",
                                                   "Gray Stained Glass",
                                                   "Gray Terracotta",
                                                   "Gray Wool",
                                                   "Green Concrete Powder",
                                                   "Green Stained Glass",
                                                   "Green Terracotta",
                                                   "Green Wool",
                                                   "Hay Block",
                                                   "Iron Block",
                                                   "Jack o' Lantern",
                                                   "Jungle Planks",
                                                   "Jungle Slab",
                                                   "Jungle Stairs",
                                                   "Jungle Wood",
                                                   "Lapis Block",
                                                   "Light Blue Concrete Powder",
                                                   "Light Blue Stained Glass",
                                                   "Light Blue Terracotta",
                                                   "Light Blue Wool",
                                                   "Light Gray Concrete Powder",
                                                   "Light Gray Stained Glass",
                                                   "Light Gray Terracotta",
                                                   "Light Gray Wool",
                                                   "Lime Concrete Powder",
                                                   "Lime Stained Glass",
                                                   "Lime Terracotta",
                                                   "Lime Wool",
                                                   "Magenta Concrete Powder",
                                                   "Magenta Stained Glass",
                                                   "Magenta Terracotta",
                                                   "Magenta Wool",
                                                   "Magma Block",
                                                   "Melon",
                                                   "Mossy Cobblestone",
                                                   "Mossy Cobblestone Slab",
                                                   "Mossy Cobblestone Slab (Stonecutter)",
                                                   "Mossy Cobblestone Stairs",
                                                   "Mossy Cobblestone Stairs (Stonecutter)",
                                                   "Mossy Stone Brick Slab",
                                                   "Mossy Stone Brick Slab (Stonecutter)",
                                                   "Mossy Stone Brick Stairs",
                                                   "Mossy Stone Brick Stairs (Stonecutter)",
                                                   "Mossy Stone Bricks",
                                                   "Nether Brick Slab",
                                                   "Nether Brick Slab (Stonecutter)",
                                                   "Nether Brick Stairs",
                                                   "Nether Brick Stairs (Stonecutter)",
                                                   "Nether Bricks",
                                                   "Nether Wart Block",
                                                   "Netherite Block",
                                                   "Oak Planks",
                                                   "Oak Slab",
                                                   "Oak Stairs",
                                                   "Oak Wood",
                                                   "Orange Concrete Powder",
                                                   "Orange Stained Glass",
                                                   "Orange Terracotta",
                                                   "Orange Wool",
                                                   "Packed Ice",
                                                   "Pink Concrete Powder",
                                                   "Pink Stained Glass",
                                                   "Pink Terracotta",
                                                   "Pink Wool",
                                                   "Polished Andesite",
                                                   "Polished Andesite (Stonecutter)",
                                                   "Polished Andesite Slab",
                                                   "Polished Andesite Slab (Stonecutter (from Andesite))",
                                                   "Polished Andesite Slab (Stonecutter (from Polished Andesite))",
                                                   "Polished Andesite Stairs",
                                                   "Polished Andesite Stairs (Stonecutter (from Andesite))",
                                                   "Polished Andesite Stairs (Stonecutter (from Polished Andesite))",
                                                   "Polished Basalt",
                                                   "Polished Basalt (Stonecutter)",
                                                   "Polished Blackstone",
                                                   "Polished Blackstone (Stonecutter)",
                                                   "Polished Blackstone Brick Slab",
                                                   "Polished Blackstone Brick Slab (Stonecutter (from Blackstone))",
                                                   "Polished Blackstone Brick Slab (Stonecutter (from Polished Blackstone Bricks))",
                                                   "Polished Blackstone Brick Slab (Stonecutter (from Polished Blackstone))",
                                                   "Polished Blackstone Brick Stairs",
                                                   "Polished Blackstone Brick Stairs (Stonecutter (from Blackstone))",
                                                   "Polished Blackstone Brick Stairs (Stonecutter (from Polished Blackstone Bricks))",
                                                   "Polished Blackstone Brick Stairs (Stonecutter (from Polished Blackstone))",
                                                   "Polished Blackstone Bricks",
                                                   "Polished Blackstone Bricks (Stonecutter (from Blackstone))",
                                                   "Polished Blackstone Bricks (Stonecutter (from Polished Blackstone))",
                                                   "Polished Blackstone Slab",
                                                   "Polished Blackstone Slab (Stonecutter (from Blackstone))",
                                                   "Polished Blackstone Slab (Stonecutter (from Polished Blackstone))",
                                                   "Polished Blackstone Stairs",
                                                   "Polished Blackstone Stairs (Stonecutter (from Blackstone))",
                                                   "Polished Blackstone Stairs (Stonecutter (from Polished Blackstone))",
                                                   "Polished Diorite",
                                                   "Polished Diorite (Stonecutter)",
                                                   "Polished Diorite Slab (Stonecutter (from Diorite))",
                                                   "Polished Diorite Slab (Stonecutter (from Polished Diorite))",
                                                   "Polished Diorite Stairs",
                                                   "Polished Diorite Stairs (Stonecutter (from Diorite))",
                                                   "Polished Diorite Stairs (Stonecutter (from Polished Diorite))",
                                                   "Polished Granite",
                                                   "Polished Granite (Stonecutter)",
                                                   "Polished Granite Slab",
                                                   "Polished Granite Slab (Stonecutter (from Granite))",
                                                   "Polished Granite Slab (Stonecutter (from Polished Granite))",
                                                   "Polished Granite Stairs",
                                                   "Polished Granite Stairs (Stonecutter (from Granite))",
                                                   "Polished Granite Stairs (Stonecutter (from Polished Granite))",
                                                   "Prismarine",
                                                   "Prismarine Brick Slab",
                                                   "Prismarine Brick Slab (Stonecutter)",
                                                   "Prismarine Brick Stairs",
                                                   "Prismarine Brick Stairs (Stonecutter)",
                                                   "Prismarine Bricks",
                                                   "Prismarine Slab",
                                                   "Prismarine Slab (Stonecutter)",
                                                   "Prismarine Stairs",
                                                   "Prismarine Stairs (Stonecutter)",
                                                   "Purple Concrete Powder",
                                                   "Purple Stained Glass",
                                                   "Purple Terracotta",
                                                   "Purple Wool",
                                                   "Purpur Block",
                                                   "Purpur Pillar",
                                                   "Purpur Pillar (Stonecutter)",
                                                   "Purpur Slab",
                                                   "Purpur Slab (Stonecutter)",
                                                   "Purpur Stairs",
                                                   "Purpur Stairs (Stonecutter)",
                                                   "Quartz Block",
                                                   "Quartz Bricks",
                                                   "Quartz Bricks (Stonecutter)",
                                                   "Quartz Pillar",
                                                   "Quartz Pillar (Stonecutter)",
                                                   "Quartz Slab",
                                                   "Quartz Slab (Stonecutter)",
                                                   "Quartz Stairs",
                                                   "Quartz Stairs (Stonecutter)",
                                                   "Red Concrete Powder",
                                                   "Red Nether Brick Slab",
                                                   "Red Nether Brick Slab (Stonecutter)",
                                                   "Red Nether Brick Stairs",
                                                   "Red Nether Brick Stairs (Stonecutter)",
                                                   "Red Nether Bricks",
                                                   "Red Sandstone",
                                                   "Red Sandstone Slab",
                                                   "Red Sandstone Slab (Stonecutter)",
                                                   "Red Sandstone Stairs",
                                                   "Red Sandstone Stairs (Stonecutter)",
                                                   "Red Stained Glass",
                                                   "Red Terracotta",
                                                   "Red Wool",
                                                   "Sandstone",
                                                   "Sandstone Slab",
                                                   "Sandstone Slab (Stonecutter)",
                                                   "Sandstone Stairs",
                                                   "Sandstone Stairs (Stonecutter)",
                                                   "Sea Lantern",
                                                   "Smooth Quartz",
                                                   "Smooth Quartz Slab",
                                                   "Smooth Quartz Slab (Stonecutter)",
                                                   "Smooth Quartz Stairs",
                                                   "Smooth Quartz Stairs (Stonecutter)",
                                                   "Smooth Red Sandstone",
                                                   "Smooth Red Sandstone Slab",
                                                   "Smooth Red Sandstone Slab (Stonecutter)",
                                                   "Smooth Red Sandstone Stairs",
                                                   "Smooth Red Sandstone Stairs (Stonecutter)",
                                                   "Smooth Sandstone",
                                                   "Smooth Sandstone Slab",
                                                   "Smooth Sandstone Slab (Stonecutter)",
                                                   "Smooth Sandstone Stairs",
                                                   "Smooth Sandstone Stairs (Stonecutter)",
                                                   "Smooth Stone",
                                                   "Smooth Stone Slab",
                                                   "Smooth Stone Slab (Stonecutter)",
                                                   "Snow Block",
                                                   "Sponge",
                                                   "Spruce Planks",
                                                   "Spruce Slab",
                                                   "Spruce Stairs",
                                                   "Spruce Wood",
                                                   "Stone",
                                                   "Stone Brick Slab",
                                                   "Stone Brick Slab (Stonecutter (from Stone Bricks))",
                                                   "Stone Brick Slab (Stonecutter (from Stone))",
                                                   "Stone Brick Stairs",
                                                   "Stone Brick Stairs (Stonecutter (from Stone Bricks))",
                                                   "Stone Brick Stairs (Stonecutter (from Stone))",
                                                   "Stone Bricks",
                                                   "Stone Bricks (Stonecutter)",
                                                   "Stone Slab",
                                                   "Stone Slab (Stonecutter",
                                                   "Stone Stairs",
                                                   "Stone Stairs (Stonecutter)",
                                                   "Stripped Acacia Wood",
                                                   "Stripped Birch Wood",
                                                   "Stripped Crimson Hyphae",
                                                   "Stripped Dark Oak Wood",
                                                   "Stripped Jungle Wood",
                                                   "Stripped Oak Wood",
                                                   "Stripped Spruce Wood",
                                                   "Stripped Warped Hyphae",
                                                   "Terracotta",
                                                   "Warped Hyphae",
                                                   "Warped Planks",
                                                   "Warped Slab",
                                                   "Warped Stairs",
                                                   "White Concrete Powder",
                                                   "White Stained Glass",
                                                   "White Terracotta",
                                                   "White Wool",
                                                   "Yellow Concrete Powder",
                                                   "Yellow Stained Glass",
                                                   "Yellow Terracotta",
                                                   "Yellow Wool"
                                                 };
        public static string[] RecipesDecoration = { "Acacia Fence",
                                                     "Acacia Sign",
                                                     "Andesite Wall",
                                                     "Andesite Wall (Stonecutter)",
                                                     "Anvil",
                                                     "Armor Stand",
                                                     "Barrel",
                                                     "Beehive",
                                                     "Birch Fence",
                                                     "Birch Sign",
                                                     "Black Banner",
                                                     "Black Bed",
                                                     "Black Bed (Coloring)",
                                                     "Black Carpet",
                                                     "Black Carpet (Coloring)",
                                                     "Black Glazed Terracotta",
                                                     "Black Stained Glass Pane",
                                                     "Black Stained Glass Pane (Coloring)",
                                                     "Blackstone Wall",
                                                     "Blackstone wall (Stonecutter)",
                                                     "Blast Furnace",
                                                     "Blue Banner",
                                                     "Blue Bed",
                                                     "Blue Bed (Coloring)",
                                                     "Blue Carpet",
                                                     "Blue Carpet (Coloring)",
                                                     "Blue Glazed Terracotta",
                                                     "Blue Stained Glass Pane",
                                                     "Blue Stained Glass Pane (Coloring)",
                                                     "Brick Wall",
                                                     "Brick Wall (Stonecutter)",
                                                     "Brown Banner",
                                                     "Brown Bed",
                                                     "Brown Bed (Coloring)",
                                                     "Brown Carpet",
                                                     "Brown Carpet (Coloring)",
                                                     "Brown Glazed Terracotta",
                                                     "Brown Stained Glass Pane",
                                                     "Brown Stained Glass Pane (Coloring)",
                                                     "Campfire",
                                                     "Cartography Table",
                                                     "Chain",
                                                     "Chest",
                                                     "Cobblestone Wall",
                                                     "Cobblestone Wall (Stonecutter)",
                                                     "Composter",
                                                     "Crafting Table",
                                                     "Crimson Fence",
                                                     "Crimson Sign",
                                                     "Cyan Banner",
                                                     "Cyan Bed",
                                                     "Cyan Bed (Coloring)",
                                                     "Cyan Carpet",
                                                     "Cyan Carped (Coloring)",
                                                     "Cyan Glazed Terracotta",
                                                     "Cyan Stained Glass Pane",
                                                     "Cyan Stained Glass Pane (Coloring)",
                                                     "Dark Oak Fence",
                                                     "Dark Oak Sign",
                                                     "Diorite Wall",
                                                     "Diorite Wall (Stonecutter)",
                                                     "Enchanting Table",
                                                     "End Crystal",
                                                     "End Rod",
                                                     "End Stone Brick Wall",
                                                     "End Stone Brick Wall (Stonecutter (from End Stone Bricks))",
                                                     "End Stone Brick Wall (Stonecutter (from End Stone))",
                                                     "Ender Chest",
                                                     "Fletching Table",
                                                     "Flower Pot",
                                                     "Furnace",
                                                     "Glass Pane",
                                                     "Granite Wall",
                                                     "Granite Wall (Stonecutter)",
                                                     "Gray Banner",
                                                     "Gray Bed",
                                                     "Gray Bed (Coloring)",
                                                     "Gray Carpet",
                                                     "Gray Carpet (Coloring)",
                                                     "Gray Glazed Terracotta",
                                                     "Gray Stained Glass Pane",
                                                     "Gray Stained Glass Pane (Coloring)",
                                                     "Green Banner",
                                                     "Green Bed",
                                                     "Green Bed (Coloring)",
                                                     "Green Carpet",
                                                     "Green Carpet (Coloring)",
                                                     "Green Glazed Terracotta",
                                                     "Green Stained Glass Pane",
                                                     "Green Stained Glass Pane (Coloring)",
                                                     "Grindstone",
                                                     "Honey Block",
                                                     "Honeycomb Block",
                                                     "Iron Bars",
                                                     "Item Frame",
                                                     "Jukebox",
                                                     "Jungle Fence",
                                                     "Jungle Sign",
                                                     "Ladder",
                                                     "Lantern",
                                                     "Light Blue Banner",
                                                     "Light Blue Bed",
                                                     "Light Blue Bed (Coloring)",
                                                     "Light Blue Carpet",
                                                     "Light Blue Carpet (Coloring)",
                                                     "Light Blue Glazed Terracotta",
                                                     "Light Blue Stained Glass Pane",
                                                     "Light Blue Stained Glass Pane (Coloring)",
                                                     "Light Gray Banner",
                                                     "Light Gray Bed",
                                                     "Light Gray Bed (Coloring)",
                                                     "Light Gray Carpet",
                                                     "Light Gray Carpet (Coloring)",
                                                     "Light Gray Glazed Terracotta",
                                                     "Light Gray Stained Glass Pane",
                                                     "Light Gray Stained Glass Pane (Coloring)",
                                                     "Lime Banner",
                                                     "Lime Bed",
                                                     "Lime Bed (Coloring)",
                                                     "Lime Carpet",
                                                     "Lime Carpet (Coloring)",
                                                     "Lime Glazed Terracotta",
                                                     "Lime Stained Glass Pane",
                                                     "Lime Stained Glass Pane (Coloring)",
                                                     "Lodestone",
                                                     "Loom",
                                                     "Magenta Banner",
                                                     "Magenta Bed",
                                                     "Magenta Bed (Coloring)",
                                                     "Magenta Carpet",
                                                     "Magenta Carpet (Coloring)",
                                                     "Magenta Glazed Terracotta",
                                                     "Magenta Stained Glass Pane",
                                                     "Magenta Stained Glass Pane (Coloring)",
                                                     "Mossy Cobblestone Wall",
                                                     "Mossy Cobblestone Wall (Stonecutter)",
                                                     "Mossy Stone Brick Wall",
                                                     "Mossy Stone Brick Wall (Stonecutter)",
                                                     "Nether Brick Fence",
                                                     "Nether Brick Wall",
                                                     "Nether Brick Wall (Stonecutter)",
                                                     "Oak Fence",
                                                     "Oak Sign",
                                                     "Orange Banner",
                                                     "Orange Bed",
                                                     "Orange Bed (Coloring)",
                                                     "Orange Carpet",
                                                     "Orange Carpet (Coloring)",
                                                     "Orange Glazed Terracotta",
                                                     "Orange Stained Glass Pane",
                                                     "Orange Stained Glass Pane (Coloring)",
                                                     "Painting",
                                                     "Pink Banner",
                                                     "Pink Bed",
                                                     "Pink Bed (Coloring)",
                                                     "Pink Carpet",
                                                     "Pink Carpet (Coloring)",
                                                     "Pink Glazed Terracotta",
                                                     "Pink Stained Glass Pane",
                                                     "Pink Stained Glass Pane (Coloring)",
                                                     "Polished Blackstone Brick Wall",
                                                     "Polished Blackstone Brick Wall (Stonecutter (from Blackstone))",
                                                     "Polished Blackstone Brick Wall (Stonecutter (from Polished Blackstone Bricks))",
                                                     "Polished Blackstone Brick Wall (Stonecutter (from Polished Blackstone))",
                                                     "Polished Blackstone Wall",
                                                     "Polished Blackstone Wall (Stonecutter (from Blackstone))",
                                                     "Polished Blackstone Wall (Stonecutter (from Polished Blackstone))",
                                                     "Prismarine Wall",
                                                     "Prismarine Wall (Stonecutter)",
                                                     "Purple Banner",
                                                     "Purple Bed",
                                                     "Purple Bed (Coloring)",
                                                     "Purple Carpet",
                                                     "Purple Carpet (Coloring)",
                                                     "Purple Glazed Terracotta",
                                                     "Purple Stained Glass Pane",
                                                     "Purple Stained Glass Pane (Coloring)",
                                                     "Red Banner",
                                                     "Red Bed",
                                                     "Red Bed (Coloring)",
                                                     "Red Carpet",
                                                     "Red Carpet (Coloring)",
                                                     "Red Glazed Terracotta",
                                                     "Red Nether Brick Wall",
                                                     "Red Nether Brick Wall (Stonecutter)",
                                                     "Red Sandstone Wall",
                                                     "Red Sandstone Wall (Stonecutter)",
                                                     "Red Stained Glass Pane",
                                                     "Red Stained Glass Pane (Coloring)",
                                                     "Respawn Anchor",
                                                     "Sandstone Wall",
                                                     "Sandstone Wall (Stonecutter)",
                                                     "Scaffolding",
                                                     "Shulker Box",
                                                     "Slime Block",
                                                     "Smithing Table",
                                                     "Smoker",
                                                     "Snow",
                                                     "Soul Campfire",
                                                     "Soul Lantern",
                                                     "Soul Torch",
                                                     "Spruce Fence",
                                                     "Spruce Sign",
                                                     "Stone Brick Wall",
                                                     "Stone Brick Wall (Stonecutter (from Stone Bricks))",
                                                     "Stone Brick Wall (Stonecutter (from Stone))",
                                                     "Stonecutter",
                                                     "Torch",
                                                     "Warped Fence",
                                                     "Warped Sign",
                                                     "White Banner",
                                                     "White Bed",
                                                     "White Carpet",
                                                     "White Glazed Terracotta",
                                                     "White Stained Glass Pane",
                                                     "White Stained Glass Pane (Coloring)",
                                                     "Yellow Banner",
                                                     "Yellow Bed",
                                                     "Yellow Bed (Coloring)",
                                                     "Yellow Carpet",
                                                     "Yellow Carpet (Coloring)",
                                                     "Yellow Glazed Terracotta",
                                                     "Yellow Stained Glass Pane",
                                                     "Yellow Stained Glass Pane (Coloring)"
                                                   };
        
        public static string[] RecipesRedstone = { "Acacia Button",
                                                   "Acacia Door",
                                                   "Acacia Fence Gate",
                                                   "Acacia Pressure Plate",
                                                   "Acacia Trapdoor",
                                                   "Birch Button",
                                                   "Birch Door",
                                                   "Birch Fence Gate",
                                                   "Birch Pressure Plate",
                                                   "Birch Trapdoor",
                                                   "Comparator",
                                                   "Crimson Button",
                                                   "Crimson Door",
                                                   "Crimson Fence Gate",
                                                   "Crimson Pressure Plate",
                                                   "Crimson Trapdoor",
                                                   "Dark Oak Button",
                                                   "Dark Oak Door",
                                                   "Dark Oak Fence Gate",
                                                   "Dark Oak Pressure Plate",
                                                   "Dark Oak Trapdoor",
                                                   "Daylight Detector",
                                                   "Dispenser",
                                                   "Dropper",
                                                   "Heavy Weighted Pressure Plate",
                                                   "Hopper",
                                                   "Iron Door",
                                                   "Iron Trapdoor",
                                                   "Jungle Button",
                                                   "Jungle Door",
                                                   "Jungle Fence Gate",
                                                   "Jungle Pressure Plate",
                                                   "Jungle Trapdoor",
                                                   "Lectern",
                                                   "Lever",
                                                   "Light Weighted Pressure Plate",
                                                   "Note Block",
                                                   "Oak Button",
                                                   "Oak Door",
                                                   "Oak Fence Gate",
                                                   "Oak Pressure Plate",
                                                   "Oak Trapdoor",
                                                   "Observer",
                                                   "Piston",
                                                   "Polished Blackstone Button",
                                                   "Polished Blackstone Pressure Plate",
                                                   "Redstone",
                                                   "Redstone Block",
                                                   "Redstone (Blasting)",
                                                   "Redstone (Smelting)",
                                                   "Redstone Lamp",
                                                   "Redstone Torch",
                                                   "Repeater",
                                                   "Spruce Button",
                                                   "Spruce Door",
                                                   "Spruce Fence Gate",
                                                   "Spruce Pressure Plate",
                                                   "Spruce Trapdoor",
                                                   "Sticky Piston",
                                                   "Stone Button",
                                                   "Stone Pressure Plate",
                                                   "Target",
                                                   "TNT",
                                                   "Trapped Chest",
                                                   "Tripwire Hook",
                                                   "Warped Button",
                                                   "Warped Door",
                                                   "Warped Fence Gate",
                                                   "Warped Pressure Plate",
                                                   "Warped Trapdoor"
                                                 };
        public static string[] RecipesTransportation = { "Acacia Boat",
                                                         "Activator Rail",
                                                         "Birch Boat",
                                                         "Carrot On A Stick",
                                                         "Chest Minecart",
                                                         "Dark Oak Boat",
                                                         "Detector Rail",
                                                         "Furnace Minecart",
                                                         "Hopper Minecart",
                                                         "Jungle Boat",
                                                         "Minecart",
                                                         "Oak Boat",
                                                         "Powered Rail",
                                                         "Rail",
                                                         "Spruce Boat",
                                                         "TNT Minecart",
                                                         "Warped Fungus On A Stick"
                                                       };
        public static string[] RecipesMisc = { "Beacon",
                                               "Black Dye (Ink Sac)",
                                               "Black Dye (Wither Rose)",
                                               "Blue Dye (Lapis)",
                                               "Blue Dye (Cornflower)",
                                               "Bone Meal (Bone)",
                                               "Bone Meal (Bone Block)",
                                               "Book",
                                               "Bowl",
                                               "Brick",
                                               "Brown Dye",
                                               "Bucket",
                                               "Charcoal",
                                               "Coal",
                                               "Coal (Blasting)",
                                               "Coal (Smelting)",
                                               "Conduit",
                                               "Creeper Banner Pattern",
                                               "Cyan Dye",
                                               "Diamond",
                                               "Diamond (Blasting)",
                                               "Diamond (Smelting)",
                                               "Emerald",
                                               "Emerald (Blasting)",
                                               "Emerald (Smelting)",
                                               "Ender Eye",
                                               "Fire Charge",
                                               "Flower Banner Pattern",
                                               "Gold Ingot",
                                               "Gold Ingot (Blasting)",
                                               "Gold Ingot (Gold Block)",
                                               "Gold Ingot (Gold Nugget)",
                                               "Gold Nugget",
                                               "Gold Nugget (Blasting)",
                                               "Gold Nugget (Smelting)",
                                               "Gray Dye",
                                               "Green Dye",
                                               "Iron Ingot",
                                               "Iron Ingot (Blasting)",
                                               "Iron Ingot (Iron Block)",
                                               "Iron Ingot (Iron Nugget)",
                                               "Iron Nugget",
                                               "Iron Nugget (Blasting)",
                                               "Iron Nugget (Smelting)",
                                               "Lapis (Blasting)",
                                               "Lapis (Smelting)",
                                               "Lapis Lazuli",
                                               "Leather",
                                               "Leather Horse Armor",
                                               "Light Blue Dye (Blue Orchid)",
                                               "Light Blue Dye (Blue x White)",
                                               "Light Gray Dye (Azure Bluet)",
                                               "Light Gray Dye (Black x White)",
                                               "Light Gray Dye (Gray x White)",
                                               "Light Gray Dye (Oxeye Daisy)",
                                               "Light Gray Dye (White Tulip)",
                                               "Lime Dye",
                                               "Lime Dye (Smelting)",
                                               "Magenta Dye (Allium)",
                                               "Magenta Dye (Blue x Red x Pink)",
                                               "Magenta Dye (Blue x Red x White)",
                                               "Magenta Dye (Lilac)",
                                               "Magenta Dye (Purple x Pink)",
                                               "Map",
                                               "Melon Seeds",
                                               "Mojang Banner Pattern",
                                               "Nether Brick",
                                               "Netherite Ingot",
                                               "Netherite Ingot (Netherite Block)",
                                               "Netherite Scrap",
                                               "Netherite Scrap (Blasting)",
                                               "Orange Dye (Orange Tulip)",
                                               "Orange Dye (Red x Yellow)",
                                               "Paper",
                                               "Pink Dye (Peony)",
                                               "Pink Dye (Pink Tulip)",
                                               "Pink Dye (Red x White)",
                                               "Popped Chorus Fruit",
                                               "Pumpkin Seeds",
                                               "Purple Dye",
                                               "Quartz",
                                               "Quartz (Blasting)",
                                               "Red Dye (Beetroot)",
                                               "Red Dye (Poppy)",
                                               "Red Dye (Rose Bush)",
                                               "Red Dye (Tulip)",
                                               "Skull Banner Pattern",
                                               "Slime Ball",
                                               "Stick",
                                               "Stick (Bamboo)",
                                               "Sugar (Honey)",
                                               "Sugar (Sugar Cane)",
                                               "Wheat",
                                               "White Dye",
                                               "White Dye (Lily of the Valley)",
                                               "Writable Book",
                                               "Yellow Dye (Dandelion)",
                                               "Yellow Dye (Sunflower)"
                                             };
        public static string[] RecipesFood = { "Baked Potato",
                                               "Baked Potato (Campfire)",
                                               "Baked Potato (Smoking)",
                                               "Beetroot Soup",
                                               "Bread",
                                               "Cake",
                                               "Cooked Beef",
                                               "Cooked Beef (Campfire)",
                                               "Cooked Beef (Smoking)",
                                               "Cooked Chicken",
                                               "Cooked Chicken (Campfire)",
                                               "Cooked Chicken (Smoking)",
                                               "Cooked Cod",
                                               "Cooked Cod (Campfire)",
                                               "Cooked Cod (Smoking)",
                                               "Cooked Mutton",
                                               "Cooked Mutton (Campfire)",
                                               "Cooked Mutton (Smoking)",
                                               "Cooked Porkchop",
                                               "Cooked Porkchop (Campfire)",
                                               "Cooked Porkchop (Smoking)",
                                               "Cooked Rabbit",
                                               "Cooked Rabbit (Campfire)",
                                               "Cooked Rabbit (Smoking)",
                                               "Cooked Salmon",
                                               "Cooked Salmon (Campfire)",
                                               "Cooked Salmon (Smoking)",
                                               "Cookie",
                                               "Dried Kelp",
                                               "Dried Kelp (Campfire)",
                                               "Dried Kelp (Smelting)",
                                               "Dried Kelp (Smoking)",
                                               "Golden Apple",
                                               "Honey Bottle",
                                               "Mushroom Stew",
                                               "Pumpkin Pie",
                                               "Rabbit Stew (Brown Mushroom)",
                                               "Rabbit Stew (Red Mushroom)"
                                             };
        public static string[] RecipesTools = { "Clock",
                                                "Compass",
                                                "Diamond Axe",
                                                "Diamond Hoe",
                                                "Diamond Pickaxe",
                                                "Diamond Shovel",
                                                "Fishing Rod",
                                                "Flint and Steel",
                                                "Golden Axe",
                                                "Golden Hoe",
                                                "Golden Pickaxe",
                                                "Golden Shovel",
                                                "Iron Axe",
                                                "Iron Hoe",
                                                "Iron Pickaxe",
                                                "Iron Shovel",
                                                "Lead",
                                                "Netherite Axe",
                                                "Netherite Hoe",
                                                "Netherite Pickaxe",
                                                "Netherite Shovel",
                                                "Shears",
                                                "Stone Axe",
                                                "Stone Hoe",
                                                "Stone Pickaxe",
                                                "Stone Shovel",
                                                "Wooden Axe",
                                                "Wooden Hoe",
                                                "Wooden Pickaxe",
                                                "Wooden Shovel"
                                              };
        public static string[] RecipesCombat = { "Arrow",
                                                 "Bow",
                                                 "Crossbow",
                                                 "Diamond Boots",
                                                 "Diamond Chestplate",
                                                 "Diamond Helmet",
                                                 "Diamond Leggings",
                                                 "Diamond Sword",
                                                 "Golden Boots",
                                                 "Golden Chestplate",
                                                 "Golden Helmet",
                                                 "Golden Leggings",
                                                 "Golden Sword",
                                                 "Iron Boots",
                                                 "Iron Chestplate",
                                                 "Iron Helmet",
                                                 "Iron Leggings",
                                                 "Iron Sword",
                                                 "Leather Boots",
                                                 "Leather Chestplate",
                                                 "Leather Helmet",
                                                 "Leather Leggings",
                                                 "Netherite Boots",
                                                 "Netherite Chestplate",
                                                 "Netherite Helmet",
                                                 "Netherite Leggings",
                                                 "Netherite Sword",
                                                 "Shield",
                                                 "Spectral Arrow",
                                                 "Stone Sword",
                                                 "Turtle Helmet",
                                                 "Wooden Sword"
                                               };
        public static string[] RecipesBrewing = { "Blaze Powder",
                                                  "Brewing Stand",
                                                  "Cauldron",
                                                  "Fermented Spider Eye",
                                                  "Glass Bottle",
                                                  "Glistering Melon Slice",
                                                  "Golden Carrot",
                                                  "Magma Cream"
                                                };
    }
}
